<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vbhudhk" failures="2" tests="2" name="Test" time="95.239" errors="0" timestamp="2022-10-12T15:38:14 IST">
  <testcase classname="tests.LoginTest" name="verifyLogIn" time="38.976">
    <failure type="java.lang.AssertionError" message="did not expect [Successfull] but found [Successfull]">
      <![CDATA[java.lang.AssertionError: did not expect [Successfull] but found [Successfull]
at tests.LoginTest.verifyLogIn(LoginTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogIn -->
  <testcase classname="tests.LoginTest" name="verifyLogIn" time="39.192">
    <failure type="java.lang.AssertionError" message="did not expect [Failure] but found [Failure]">
      <![CDATA[java.lang.AssertionError: did not expect [Failure] but found [Failure]
at tests.LoginTest.verifyLogIn(LoginTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogIn -->
</testsuite> <!-- Test -->
